### ISSUE TITLE
GET request for posts from parse database S4

### ISSUE THREAD

**Issue by mlapresta** [FondApp/Fond#8]
References: 
[Parse Read Objects ](https://dashboard.back4app.com/apidocs/SPCuR1AuHye9Uax3Hz4Uf7hb5VjBzICJjVUty2rA#reading-objects)

Acceptance criteria:
- [x] Query for posts integrated into PostsFragment (Note: This is depends on #11 )
- [x] Posts show up with most recently created at top

**Comment by mlapresta** [comment]
References: 
[Parse Read Objects ](https://dashboard.back4app.com/apidocs/SPCuR1AuHye9Uax3Hz4Uf7hb5VjBzICJjVUty2rA#reading-objects)

Acceptance criteria:
- [ ] Query for posts integrated into PostsFragment (Note: This is depends on #11 )
- [ ] Posts show up with most recently created at top

**Comment by kat-kime** [comment]
Not sure why, but I'm getting an error when I try grabbing the username from the post's users.
I'm able to grab the users themselves, but when I call the getUsername() method, it says "ParseObject has no data for 'username'. Call fetchIfNeeded() to get the data."

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.fond, PID: 29770
    java.lang.IllegalStateException: ParseObject has no data for 'username'. Call fetchIfNeeded() to get the data.
        at com.parse.ParseObject.checkGetAccess(ParseObject.java:3607)
        at com.parse.ParseObject.getString(ParseObject.java:3186)
        at com.parse.ParseUser.getUsername(ParseUser.java:758)
        at com.example.fond.models.UserPost.getUsername(UserPost.java:48)
        at com.example.fond.fragments.userFeedFragment$1.done(userFeedFragment.java:77)
        at com.example.fond.fragments.userFeedFragment$1.done(userFeedFragment.java:68)
        at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:121)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I'm so confused - why would a ParseUser not have data for username? Aren't those required?

**EDIT:** This has been resolved. As directed in the error meessage, I called fetchIfNeeded() with a try/catch:
